services:
  mysql:
    image: mysql:8.0
    container_name: proyecto_taller_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: laravel
    ports:
      - "3301:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
